export type ReceiptPaperSize = 'MM58' | 'MM80';

export type RefundApprovalMethod = 'APPROVAL_ID' | 'NFC_CARD' | 'NFC_CARD_AND_PIN';

export type StoreSettings = {
  id: string;
  storeName: string;
  storePhone: string | null;
  storeAddress: string | null;
  receiptFooter: string | null;
  taxEnabled: boolean;
  taxRate: string | number;
  currency: string;
  lowStockDefault: number;
  receiptLogo: string | null;
  receiptPaperSize: ReceiptPaperSize;
  receiptAutoPrint: boolean;
  receiptCopies: number;
  receiptShowLogo: boolean;
  receiptPrinterName: string | null;
  quotationPrefix: string;
  proformaPrefix: string;
  invoicePrefix: string;
  showTaxOnQuotation: boolean;
  showSignatureArea: boolean;
  deliveryNotePrefix: string;
  defaultPaymentTermsDays: number;
  enableCustomerCredit: boolean;
  enableDeliveryNotes: boolean;
  enableApprovalWorkflow: boolean;
  allowOverCreditOverride: boolean;
  allowOverStockOverride: boolean;
  emailNotificationsEnabled: boolean;
  notifyLowStock: boolean;
  notifyInvoicePayment: boolean;
  notifyCustomerOverdue: boolean;
  notifySubscription: boolean;
  notifyDeviceActivation: boolean;
  refundApprovalMethod: RefundApprovalMethod;
  createdAt: string;
  updatedAt: string;
};

export type PatchStoreSettingsBody = Partial<{
  storeName: string;
  storePhone: string | null;
  storeAddress: string | null;
  receiptFooter: string | null;
  taxEnabled: boolean;
  taxRate: number;
  currency: string;
  lowStockDefault: number;
  receiptLogo: string | null;
  receiptPaperSize: ReceiptPaperSize;
  receiptAutoPrint: boolean;
  receiptCopies: number;
  receiptShowLogo: boolean;
  receiptPrinterName: string | null;
  quotationPrefix: string;
  proformaPrefix: string;
  invoicePrefix: string;
  showTaxOnQuotation: boolean;
  showSignatureArea: boolean;
  deliveryNotePrefix: string;
  defaultPaymentTermsDays: number;
  enableCustomerCredit: boolean;
  enableDeliveryNotes: boolean;
  enableApprovalWorkflow: boolean;
  allowOverCreditOverride: boolean;
  allowOverStockOverride: boolean;
  emailNotificationsEnabled: boolean;
  notifyLowStock: boolean;
  notifyInvoicePayment: boolean;
  notifyCustomerOverdue: boolean;
  notifySubscription: boolean;
  notifyDeviceActivation: boolean;
  refundApprovalMethod?: RefundApprovalMethod;
}>;
